name: Zerang
description: "an app for everyone"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  shamsi_date: ^1.0.2
  adaptive_theme: ^3.6.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2
  shared_preferences: ^2.2.3
  flutter_localization: ^0.2.0
  http: ^1.2.1
  iconsax: ^0.0.8
  fl_chart: ^0.68.0
<<<<<<< Updated upstream
  record: ^4.0.0
  path_provider: ^2.1.3
=======
  animate_do: ^2.0.0
  smooth_page_indicator: ^1.1.0
  nb_utils: ^6.1.0
  dots_indicator: ^2.0.0
  flutter_svg: 2.0.10+1
  url_launcher: ^6.0.12
  cached_network_image: ^3.1.0
  flutter_staggered_grid_view: ^0.4.1
  html: ^0.15.0
  intl: 0.19.0
  cupertino_icons: ^1.0.2
  connectivity_plus_web: ^1.2.5
  path_provider_windows: ^2.2.1
  shared_preferences_windows: ^2.3.2
>>>>>>> Stashed changes
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/App_Logo/Logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/App_Logo/Logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/App_Logo/Logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/App_Logo/Logo.png"

flutter:
  fonts:
    - family: Lalezar
      fonts:
        - asset: assets/Fonts/Lalezar-Regular.ttf

    - family: Iransans
      fonts:
        - asset: assets/Fonts/irsans.ttf

    - family: NotoNaskhArabicMedium
      fonts:
        - asset: assets/Fonts/NotoNaskhArabic-Medium.ttf

    - family: NotoNaskhArabicRegular
      fonts:
        - asset: assets/Fonts/NotoNaskhArabic-Regular.ttf

    - family: IRANSansX
      fonts:
        - asset: assets/Fonts/iransansX/IRANSansX-Black.ttf
          weight: 900
        - asset: assets/Fonts/iransansX/IRANSansX-Bold.ttf
          weight: 700
        - asset: assets/Fonts/iransansX/IRANSansX-DemiBold.ttf
          weight: 600
        - asset: assets/Fonts/iransansX/IRANSansX-ExtraBlack.ttf
          weight: 800
        - asset: assets/Fonts/iransansX/IRANSansX-ExtraBold.ttf
          weight: 700
        - asset: assets/Fonts/iransansX/IRANSansX-Heavy.ttf
          weight: 800
        - asset: assets/Fonts/iransansX/IRANSansX-Light.ttf
          weight: 300
        - asset: assets/Fonts/iransansX/IRANSansX-Medium.ttf
          weight: 500
        - asset: assets/Fonts/iransansX/IRANSansX-Regular.ttf
          weight: 400
        - asset: assets/Fonts/iransansX/IRANSansX-Thin.ttf
          weight: 100
        - asset: assets/Fonts/iransansX/IRANSansX-UltraLight.ttf
          weight: 200

    - family: Roboto
      fonts:
        - asset: assets/Fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/Fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
        - asset: assets/Fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
        - asset: assets/Fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/Fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/Fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
        - asset: assets/Fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
        - asset: assets/Fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/Fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100

  assets:
    - assets/splash-screen.png
    - assets/Fonts/Lalezar-Regular.ttf
    - assets/Fonts/irsans.ttf
    - assets/Fonts/NotoNaskhArabic-Medium.ttf
    - assets/Fonts/NotoNaskhArabic-Regular.ttf
    - assets/App_Logo/
    - assets/Fonts/
    - assets/Icons/
    - assets/Icons/tick.png
    - assets/photos/
    - assets/vectors/
    - assets/workout/
    - assets/workout/zerang pack/
    - assets/gifs/
    - assets/vectors/MBI/
    - assets/gifs/lotties/
    - assets/gifs/workout_gifs/
    - assets/vectors/calorie.png
    - assets/vectors/Onboarding/power.png
    - assets/vectors/Onboarding/regime.png
    - assets/vectors/Onboarding/health.png  
    - assets/Icons/feelings_icons/1x/
    - assets/workout/zerang pack
    


  uses-material-design: true
