// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJlC85N6gpYWZ9s3Y_EcHwarEeSCMLfVU',
    appId: '1:482748024871:web:756f6f2729ac1ebc626602',
    messagingSenderId: '482748024871',
    projectId: 'zerang-93c43',
    authDomain: 'zerang-93c43.firebaseapp.com',
    storageBucket: 'zerang-93c43.appspot.com',
    measurementId: 'G-KWJYTV7M5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAexFP3_JunDr-VsAuMtD34n55hKtyla8U',
    appId: '1:482748024871:android:0de835df5115af9b626602',
    messagingSenderId: '482748024871',
    projectId: 'zerang-93c43',
    storageBucket: 'zerang-93c43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmciGtxj0FI23uD0Aw4p6AZvcJc4glG8I',
    appId: '1:482748024871:ios:4775149e33e9313c626602',
    messagingSenderId: '482748024871',
    projectId: 'zerang-93c43',
    storageBucket: 'zerang-93c43.appspot.com',
    iosBundleId: 'com.example.bashgah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmciGtxj0FI23uD0Aw4p6AZvcJc4glG8I',
    appId: '1:482748024871:ios:4775149e33e9313c626602',
    messagingSenderId: '482748024871',
    projectId: 'zerang-93c43',
    storageBucket: 'zerang-93c43.appspot.com',
    iosBundleId: 'com.example.bashgah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJlC85N6gpYWZ9s3Y_EcHwarEeSCMLfVU',
    appId: '1:482748024871:web:39de7cbc472729e0626602',
    messagingSenderId: '482748024871',
    projectId: 'zerang-93c43',
    authDomain: 'zerang-93c43.firebaseapp.com',
    storageBucket: 'zerang-93c43.appspot.com',
    measurementId: 'G-6JGG67DX57',
  );
}
