// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG0wh0je0niVxivb6z1KMB57lsDENOUc0',
    appId: '1:405370794420:web:ceba66152385f98484c2e1',
    messagingSenderId: '405370794420',
    projectId: 'zerang-2d68b',
    authDomain: 'zerang-2d68b.firebaseapp.com',
    storageBucket: 'zerang-2d68b.appspot.com',
    measurementId: 'G-T68NVBBEWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1LgEHV6kwc68mc2FAbN_dJ_TCf5TFSIk',
    appId: '1:405370794420:android:911c591fc17f0ea584c2e1',
    messagingSenderId: '405370794420',
    projectId: 'zerang-2d68b',
    storageBucket: 'zerang-2d68b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGtL6IAOLhesfYyoMgx4Vow-Z67BMszkY',
    appId: '1:405370794420:ios:79cc0e9d69e9d6c184c2e1',
    messagingSenderId: '405370794420',
    projectId: 'zerang-2d68b',
    storageBucket: 'zerang-2d68b.appspot.com',
    iosBundleId: 'com.example.bashgah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGtL6IAOLhesfYyoMgx4Vow-Z67BMszkY',
    appId: '1:405370794420:ios:79cc0e9d69e9d6c184c2e1',
    messagingSenderId: '405370794420',
    projectId: 'zerang-2d68b',
    storageBucket: 'zerang-2d68b.appspot.com',
    iosBundleId: 'com.example.bashgah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG0wh0je0niVxivb6z1KMB57lsDENOUc0',
    appId: '1:405370794420:web:6f2a435b9b6ec96d84c2e1',
    messagingSenderId: '405370794420',
    projectId: 'zerang-2d68b',
    authDomain: 'zerang-2d68b.firebaseapp.com',
    storageBucket: 'zerang-2d68b.appspot.com',
    measurementId: 'G-R9EZFDCRH6',
  );
}
