name: fitness
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  shamsi_date: ^1.0.2
  adaptive_theme: ^3.6.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/App_Logo/Logo.png" 
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/App_Logo/Logo.png" 
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/App_Logo/Logo.png" 
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/App_Logo/Logo.png" 

flutter:
  fonts:
    - family: Lalezar
      fonts:
        - asset: assets/Fonts/Lalezar-Regular.ttf

    - family: Iransans
      fonts:
        - asset: assets/Fonts/irsans.ttf

    - family: NotoNaskhArabicMedium
      fonts:
        - asset: assets/Fonts/NotoNaskhArabic-Medium.ttf

    - family: NotoNaskhArabicRegular
      fonts:
        - asset: assets/Fonts/NotoNaskhArabic-Regular.ttf

  

  assets:
    - assets/splash-screen.png
    - assets/Fonts/Lalezar-Regular.ttf
    - assets/Fonts/irsans.ttf
    - assets/Fonts/NotoNaskhArabic-Medium.ttf
    - assets/Fonts/NotoNaskhArabic-Regular.ttf
    - assets/App_Logo/
    - assets/Fonts/
    - assets/Icons/
    - assets/photos/
    - assets/vectors/
    - assets/workout/

  uses-material-design: true
